import BigNumber from 'bignumber.js';

export const DEFAULT_ADDRESS = '0x0000000000000000000000000000000000000000';

export const BIG_NUMBER = {
  TEN: BigNumber(10),
  TEN_POW_18: BigNumber(10).pow(BigNumber(18)),
};

export const EthRequest = {
  getBlockByHash: 'eth_getBlockByHash',
  getBlockByNumber: 'eth_getBlockByNumber',
  getBlockTransactionCountByHash: 'eth_getBlockTransactionCountByHash',
  getBlockTransactionCountByNumber: 'eth_getBlockTransactionCountByNumber',
  getUncleCountBlockHash: 'eth_getUncleCountBlockHash',
  getUncleCountBlockNumber: 'eth_getUncleCountBlockNumber',
  chainId: 'eth_chainId',
  syncing: 'eth_syncing',
  coinbase: 'eth_coinbase',
  accounts: 'eth_accounts',
  blockNumber: 'eth_blockNumber',
  call: 'eth_call',
  estimateGas: 'eth_estimateGas',
  createAccessList: 'eth_createAccessList',
  gasPrice: 'eth_gasPrice',
  maxPriorityFeePerGas: 'eth_maxPriorityFeePerGas',
  feeHistory: 'eth_feeHistory',
  newFilter: 'eth_newFilter',
  newBlockFilter: 'eth_newBlockFilter',
  newPendingTransactionFilter: 'eth_newPendingTransactionFilter',
  uninstallFilter: 'eth_uninstallFilter',
  getFilterChanges: 'eth_getFilterChanges',
  getFilterLogs: 'eth_getFilterLogs',
  getLogs: 'eth_getLogs',
  mining: 'eth_mining',
  hashrate: 'eth_hashrate',
  getWork: 'eth_getWork',
  submitWork: 'eth_submitWork',
  submitHashrate: 'eth_submitHashrate',
  sign: 'eth_sign',
  signTransaction: 'eth_signTransaction',
  getBalance: 'eth_getBalance',
  getStorageAt: 'eth_getStorageAt',
  getTransactionCount: 'eth_getTransactionCount',
  getCode: 'eth_getCode',
  getProof: 'eth_getProof',
  sendTransaction: 'eth_sendTransaction',
  sendRawTransaction: 'eth_sendRawTransaction',
  getTransactionByHash: 'eth_getTransactionByHash',
  getTransactionByBlockHashAndIndex: 'eth_getTransactionByBlockHashAndIndex',
  getTransactionByBlockNumberAndIndex: 'eth_getTransactionByBlockNumberAndIndex',
  getTransactionReceipt: 'eth_getTransactionReceipt',
};
